apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kube-cert-manager
  name: kube-cert-manager
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stable.k8s.psg.io/kcm.class: default
        app: kube-cert-manager
      name: kube-cert-manager
    spec:
      containers:
        - name: kube-cert-manager
          image: jhanschoo/kube-cert-manager:0.5.0
          args:
            - "-data-dir=/var/lib/cert-manager"
            #- "-acme-url=https://acme-staging.api.letsencrypt.org/directory"
            # NOTE: the URL above points to the staging server, where you won't get real certs.
            # Uncomment the line below to use the production LetsEncrypt server:
            - "-acme-url=https://acme-v01.api.letsencrypt.org/directory"
            # You can run multiple instances of kube-cert-manager for the same namespace(s),
            # each watching for a different value for the 'class' label
            #- "-class=default"
            # You can choose to monitor only some namespaces, otherwise all namespaces will be monitored
            #- "-namespaces=default"
            # If you set a default email, you can omit the field/annotation from Certificates/Ingresses
            - "-default-email=admin@writerite.site"
            # If you set a default provider, you can omit the field/annotation from Certificates/Ingresses
            - "-default-provider=googlecloud"
          env:
            - name: GCE_PROJECT
              value: writerite-188405
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gac/credentials.json
          volumeMounts:
            - name: data
              mountPath: /var/lib/cert-manager
            - name: gac
              readOnly: true
              mountPath: /etc/gac
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kube-cert-manager
        - name: gac
          secret:
            secretName: wr-dns-credentials
      serviceAccount: kube-cert-manager
