kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: kube-cert-manager
  name: kube-cert-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
